### ISSUE TITLE
ssh: connect to host 175.24.121.148 port 22: No route to host

### ISSUE THREAD

**Issue by lianlipen** [BAAI-WuDao/EVA#3]
ssh: connect to host 175.24.121.148 port 22: No route to host
Traceback (most recent call last):
  File "/opt/conda/bin/deepspeed", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/runner.py", line 281, in main
    result = subprocess.check_output(hostname_cmd, shell=True)
  File "/opt/conda/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh 175.24.121.148 hostname -I']' returned non-zero exit status 255.

175.24.121.148，是我本地服务器的ip。这种情况 怎么解决了？谢谢指导！

**Comment by xiaoqiao** [comment]
应该是因为port 22的原因，你要把这个改一下，改成2222（我也还没找到怎么改）
另外就是你不应该填本地服务器的ip，应该填你docker container的ip
